name: Main Workflow
on: [push]
jobs:
  build:
    name: Run load test using the action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run load test using action code from commit
        uses: ./
        with:
          cloud: false
          flags: --vus 1 --duration 20m

